Avoid Too many arguments passed to changesets
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
/usr/bin/git checkout changeset-release/main
Switched to a new branch 'changeset-release/main'
M	.yarnrc.yml
branch 'changeset-release/main' set up to track 'origin/changeset-release/main'.
/usr/bin/git reset --hard 7a1b66fdfbffca2dd57ca93e05c4ec809b0ee1ab
HEAD is now at 7a1b66f Create thin-queens-rule.md
/opt/hostedtoolcache/node/22.11.0/x64/bin/corepack yarn changeset version && yarn
🦋  error Too many arguments passed to changesets - we only accept the command name as an argument
/usr/bin/git status --porcelain
/usr/bin/git push origin HEAD:changeset-release/main --force
remote:
remote: GitHub found 3 vulnerabilities on transloadit/monolib's default branch (2 high, 1 moderate). To find out more, visit:
remote:      https://github.com/transloadit/monolib/security/dependabot
remote:
To https://github.com/transloadit/monolib
   72c1cc5..7a1b66f  HEAD -> changeset-release/main
[]
creating pull request
Error: HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}
Error: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}

https://github.com/transloadit/monolib/actions/runs/11958917014/job/33339520219#step:8:1